"""empty message

Revision ID: 12ffb4af8d25
Revises: 2a7ea93eeaca
Create Date: 2018-09-06 19:53:47.446599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ffb4af8d25'
down_revision = '2a7ea93eeaca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.String(length=200), nullable=True),
    sa.Column('link_url', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banner')
    # ### end Alembic commands ###
