"""empty message

Revision ID: 1bee119f3d48
Revises: 68270303c680
Create Date: 2018-09-02 21:41:04.790915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bee119f3d48'
down_revision = '68270303c680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('gender', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'gender')
    # ### end Alembic commands ###
