"""empty message

Revision ID: 1c8e44417539
Revises: b66256cc250d
Create Date: 2018-10-18 16:15:46.817385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8e44417539'
down_revision = 'b66256cc250d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('weibo_id', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'weibo_id')
    # ### end Alembic commands ###
