"""empty message

Revision ID: 2762b1009215
Revises: e8c62ae10e7d
Create Date: 2018-10-13 19:18:02.719631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2762b1009215'
down_revision = 'e8c62ae10e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error', sa.Column('place', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('error', 'place')
    # ### end Alembic commands ###
