"""empty message

Revision ID: 2d37329b3185
Revises: fc6501a027be
Create Date: 2018-09-04 09:40:20.137910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d37329b3185'
down_revision = 'fc6501a027be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('focus_time', sa.DateTime(), nullable=True),
    sa.Column('own_user_id', sa.String(length=150), nullable=False),
    sa.Column('author_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['front_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('focus')
    # ### end Alembic commands ###
