"""empty message

Revision ID: 2d52f845fa8f
Revises: 8c1e09cbf1d2
Create Date: 2018-09-20 20:45:07.882696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d52f845fa8f'
down_revision = '8c1e09cbf1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'message', 'front_user', ['reciver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    # ### end Alembic commands ###
