"""empty message

Revision ID: 383797f9d1f2
Revises: 6fc91f81c121
Create Date: 2018-10-13 15:49:44.205417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383797f9d1f2'
down_revision = '6fc91f81c121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('is_using', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisement', 'is_using')
    # ### end Alembic commands ###
