"""empty message

Revision ID: 49926bd98c4a
Revises: 5fffabbb809e
Create Date: 2018-09-23 22:03:34.667917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49926bd98c4a'
down_revision = '5fffabbb809e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('img_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagname', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album_tag',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['img_tag.id'], ),
    sa.PrimaryKeyConstraint('album_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album_tag')
    op.drop_table('img_tag')
    # ### end Alembic commands ###
