"""empty message

Revision ID: 4b55bd074c1a
Revises: 49926bd98c4a
Create Date: 2018-09-24 10:59:24.134179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b55bd074c1a'
down_revision = '49926bd98c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'color')
    # ### end Alembic commands ###
