"""empty message

Revision ID: 59d35ee08e21
Revises: 9a48dfebeec0
Create Date: 2018-09-29 17:36:23.249771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d35ee08e21'
down_revision = '9a48dfebeec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('advertisement_ibfk_1', 'advertisement', type_='foreignkey')
    op.create_foreign_key(None, 'advertisement', 'cms_user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advertisement', type_='foreignkey')
    op.create_foreign_key('advertisement_ibfk_1', 'advertisement', 'front_user', ['author_id'], ['id'])
    # ### end Alembic commands ###
