"""empty message

Revision ID: 67075a9fce17
Revises: 135501cec8b9
Create Date: 2018-09-16 15:46:13.463873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67075a9fce17'
down_revision = '135501cec8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('avatar', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'avatar')
    # ### end Alembic commands ###
