"""empty message

Revision ID: 68270303c680
Revises: a5a8e03a858e
Create Date: 2018-09-02 21:06:53.264970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68270303c680'
down_revision = 'a5a8e03a858e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('old_avater', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'old_avater')
    # ### end Alembic commands ###
