"""empty message

Revision ID: 6fc91f81c121
Revises: 59d35ee08e21
Create Date: 2018-09-29 17:40:39.147171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc91f81c121'
down_revision = '59d35ee08e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'advertisement', 'cms_user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advertisement', type_='foreignkey')
    # ### end Alembic commands ###
