"""empty message

Revision ID: 82c3c2213449
Revises: 40ecfd2f5fec
Create Date: 2018-09-16 19:46:22.402095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c3c2213449'
down_revision = '40ecfd2f5fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topic', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.drop_column('topic', 'group_id')
    # ### end Alembic commands ###
