"""empty message

Revision ID: 87ca08b34a71
Revises: a5631c98af72
Create Date: 2018-09-22 20:34:41.243599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ca08b34a71'
down_revision = 'a5631c98af72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'create_time')
    # ### end Alembic commands ###
