"""empty message

Revision ID: 8e32ec69e951
Revises: 78d94aa9b4c0
Create Date: 2018-09-16 15:41:19.130226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e32ec69e951'
down_revision = '78d94aa9b4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('point', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'point')
    # ### end Alembic commands ###
