"""empty message

Revision ID: 9a45e022be57
Revises: 7d63cc94a512
Create Date: 2018-09-03 11:31:13.338691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a45e022be57'
down_revision = '7d63cc94a512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collect_time', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.String(length=150), nullable=True),
    sa.Column('author_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['front_user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('star',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=150), nullable=True),
    sa.Column('author_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['front_user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('star')
    op.drop_table('collect')
    # ### end Alembic commands ###
