"""empty message

Revision ID: 9a48dfebeec0
Revises: 4b55bd074c1a
Create Date: 2018-09-29 17:08:45.808798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a48dfebeec0'
down_revision = '4b55bd074c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('img_url', sa.String(length=400), nullable=True),
    sa.Column('link_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['front_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisement')
    # ### end Alembic commands ###
