"""empty message

Revision ID: a5631c98af72
Revises: a226d3f9db94
Create Date: 2018-09-22 14:41:11.215235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5631c98af72'
down_revision = 'a226d3f9db94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_ibfk_2', 'image', type_='foreignkey')
    op.drop_column('image', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('author_id', mysql.VARCHAR(length=150), nullable=True))
    op.create_foreign_key('image_ibfk_2', 'image', 'front_user', ['author_id'], ['id'])
    # ### end Alembic commands ###
