"""empty message

Revision ID: a5a8e03a858e
Revises: 669cc9460926
Create Date: 2018-09-02 18:14:35.999457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a8e03a858e'
down_revision = '669cc9460926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('nickname', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'nickname')
    # ### end Alembic commands ###
