"""empty message

Revision ID: b64f9a1d55c8
Revises: a1a17081190e
Create Date: 2018-09-20 22:40:29.715984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b64f9a1d55c8'
down_revision = 'a1a17081190e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('reciver_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('author_id', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['front_user.id'], name='message_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
