"""empty message

Revision ID: dac30aca2780
Revises: e0c53dff9206
Create Date: 2018-09-09 11:30:06.096139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac30aca2780'
down_revision = 'e0c53dff9206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('is_active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'is_active')
    # ### end Alembic commands ###
