"""empty message

Revision ID: e0c53dff9206
Revises: 12ffb4af8d25
Create Date: 2018-09-08 14:43:40.430039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c53dff9206'
down_revision = '12ffb4af8d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('charactors', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'charactors')
    # ### end Alembic commands ###
