"""empty message

Revision ID: e3cd29b93101
Revises: b3305809899d
Create Date: 2018-09-15 20:58:58.932331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cd29b93101'
down_revision = 'b3305809899d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('address', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'address')
    # ### end Alembic commands ###
